name = "Minecraft Fabric RPG - PAPUS2.0"
author = "Antony"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21065f5faa0688675511a03661b08361fcbebb0f04c0b4398522b54d65ecf6ed"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
